name: 🐛 Bug report
description: Submit a bug report to help improve this project
title: "[🐛 Bug report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report.
  - type: textarea
    id: describtion
    attributes:
      label: Reproduction steps
      description: Tell me what you did to trigger this bug
      placeholder: When I...
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What did you think would happen?
      placeholder:  It should...
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: What did actually happen? Feel free to add screenshots.
      placeholder: It actually did...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What OS is your device running on?
      options:
        - Linux
        - MacOS
        - Windows
        - Something else
    validations:
      required: true
  - type: checkboxes
    id: no-duplicates
    attributes:
      label: Have you spend some time to make sure no similar issue already exists?
      description: Please make sure to at least google if something similar already happended to someone else
      options:
        - label: I checked and didn't find a similar issue
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I would like to help implementing this
      description: I'm always looking for people that can help out
      options:
        - label: If you would like to help implement this feature tick the box
          required: false
